% -------------------------------------------------------------------
%  Generated by MATLAB on 30-Jan-2023 16:10:37
%  MATLAB version: 9.12.0.2039608 (R2022a) Update 5
% -------------------------------------------------------------------
saveVarsMat = load('Final_Assembly_No_Gears_DataFile.mat');


smiData = saveVarsMat.smiData; % <1x1 struct> unsupported class at smiData.RigidTransform(1).ID

clear saveVarsMat;